apiVersion: v1
kind: Service
metadata:
  name: distributed-system-api-service
  namespace: distributed-systems
  labels:
    app: distributed-system-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: distributed-system-api
